"""initial

Revision ID: df8a1a389a44
Revises: 
Create Date: 2026-04-09 14:12:59.416447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df8a1a389a44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE SCHEMA IF NOT EXISTS identity")
    op.execute("CREATE SCHEMA IF NOT EXISTS raw")
    op.execute("CREATE SCHEMA IF NOT EXISTS normalized")
    
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_users_email'), 'users', ['email'], unique=True, schema='identity')
    op.create_table('jira_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_integration_id', sa.Integer(), nullable=True),
    sa.Column('issue_key', sa.String(length=255), nullable=False),
    sa.Column('project_key', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('status_category', sa.String(length=50), nullable=True),
    sa.Column('assignee_account_id', sa.String(length=255), nullable=True),
    sa.Column('assignee_name', sa.String(length=255), nullable=True),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('reporter_account_id', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('story_points', sa.Float(), nullable=True),
    sa.Column('original_estimate', sa.Float(), nullable=True),
    sa.Column('time_spent', sa.Float(), nullable=True),
    sa.Column('remaining_estimate', sa.Float(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('snapshot_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='normalized'
    )
    op.create_index(op.f('ix_normalized_jira_issues_assignee_account_id'), 'jira_issues', ['assignee_account_id'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_jira_issues_issue_key'), 'jira_issues', ['issue_key'], unique=True, schema='normalized')
    op.create_index(op.f('ix_normalized_jira_issues_project_integration_id'), 'jira_issues', ['project_integration_id'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_jira_issues_project_key'), 'jira_issues', ['project_key'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_jira_issues_status'), 'jira_issues', ['status'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_jira_issues_updated_at'), 'jira_issues', ['updated_at'], unique=False, schema='normalized')
    op.create_table('raw_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('project_integration_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_index('idx_raw_events_source_external', 'raw_events', ['source', 'external_id'], unique=False, schema='raw')
    op.create_index('idx_raw_events_timestamp', 'raw_events', ['timestamp'], unique=False, schema='raw')
    op.create_index(op.f('ix_raw_raw_events_event_type'), 'raw_events', ['event_type'], unique=False, schema='raw')
    op.create_index(op.f('ix_raw_raw_events_external_id'), 'raw_events', ['external_id'], unique=False, schema='raw')
    op.create_index(op.f('ix_raw_raw_events_source'), 'raw_events', ['source'], unique=False, schema='raw')
    op.create_index(op.f('ix_raw_raw_events_timestamp'), 'raw_events', ['timestamp'], unique=False, schema='raw')
    op.create_table('integration_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('instance_id', sa.String(length=255), nullable=False),
    sa.Column('instance_name', sa.String(length=255), nullable=True),
    sa.Column('instance_url', sa.String(length=500), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'instance_id', name='uq_user_provider_instance'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_integration_tokens_instance_id'), 'integration_tokens', ['instance_id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_integration_tokens_provider'), 'integration_tokens', ['provider'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_integration_tokens_provider_user_id'), 'integration_tokens', ['provider_user_id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_integration_tokens_user_id'), 'integration_tokens', ['user_id'], unique=False, schema='identity')
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('client_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_sessions_session_token'), 'sessions', ['session_token'], unique=True, schema='identity')
    op.create_index(op.f('ix_identity_sessions_user_id'), 'sessions', ['user_id'], unique=False, schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_sessions_user_id'), table_name='sessions', schema='identity')
    op.drop_index(op.f('ix_identity_sessions_session_token'), table_name='sessions', schema='identity')
    op.drop_table('sessions', schema='identity')
    op.drop_index(op.f('ix_identity_integration_tokens_user_id'), table_name='integration_tokens', schema='identity')
    op.drop_index(op.f('ix_identity_integration_tokens_provider_user_id'), table_name='integration_tokens', schema='identity')
    op.drop_index(op.f('ix_identity_integration_tokens_provider'), table_name='integration_tokens', schema='identity')
    op.drop_index(op.f('ix_identity_integration_tokens_instance_id'), table_name='integration_tokens', schema='identity')
    op.drop_table('integration_tokens', schema='identity')
    op.drop_index(op.f('ix_raw_raw_events_timestamp'), table_name='raw_events', schema='raw')
    op.drop_index(op.f('ix_raw_raw_events_source'), table_name='raw_events', schema='raw')
    op.drop_index(op.f('ix_raw_raw_events_external_id'), table_name='raw_events', schema='raw')
    op.drop_index(op.f('ix_raw_raw_events_event_type'), table_name='raw_events', schema='raw')
    op.drop_index('idx_raw_events_timestamp', table_name='raw_events', schema='raw')
    op.drop_index('idx_raw_events_source_external', table_name='raw_events', schema='raw')
    op.drop_table('raw_events', schema='raw')
    op.drop_index(op.f('ix_normalized_jira_issues_updated_at'), table_name='jira_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_jira_issues_status'), table_name='jira_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_jira_issues_project_key'), table_name='jira_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_jira_issues_project_integration_id'), table_name='jira_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_jira_issues_issue_key'), table_name='jira_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_jira_issues_assignee_account_id'), table_name='jira_issues', schema='normalized')
    op.drop_table('jira_issues', schema='normalized')
    op.drop_index(op.f('ix_identity_users_email'), table_name='users', schema='identity')
    op.drop_table('users', schema='identity')
    # ### end Alembic commands ###
