"""make_account_id_required

Revision ID: 220b7ac7ce24
Revises: c47b0d23d3a3
Create Date: 2026-03-30 07:30:28.260270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220b7ac7ce24'
down_revision: Union[str, Sequence[str], None] = 'c47b0d23d3a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atlassian_tokens', sa.Column('site_name', sa.String(), nullable=True))
    op.alter_column('atlassian_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('atlassian_tokens', 'atlassian_account_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('atlassian_tokens', 'cloud_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('atlassian_tokens', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('atlassian_tokens', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_atlassian_tokens_expires_at'), 'atlassian_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_atlassian_tokens_id'), 'atlassian_tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atlassian_tokens_id'), table_name='atlassian_tokens')
    op.drop_index(op.f('ix_atlassian_tokens_expires_at'), table_name='atlassian_tokens')
    op.alter_column('atlassian_tokens', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('atlassian_tokens', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('atlassian_tokens', 'cloud_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('atlassian_tokens', 'atlassian_account_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('atlassian_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('atlassian_tokens', 'site_name')
    # ### end Alembic commands ###
