"""initial_all_tables

Revision ID: 4790b6f2a61e
Revises: 
Create Date: 2026-05-22 08:51:54.680535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4790b6f2a61e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("COMMIT")
    op.execute("CREATE SCHEMA IF NOT EXISTS identity")
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.execute("CREATE SCHEMA IF NOT EXISTS raw")
    op.execute("CREATE SCHEMA IF NOT EXISTS normalized")
    op.execute("BEGIN")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_users_email'), 'users', ['email'], unique=True, schema='identity')
    op.create_table('confluence_pages',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('space_id', sa.String(length=50), nullable=False),
    sa.Column('space_key', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_format', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='normalized'
    )
    op.create_index('idx_confluence_pages_author', 'confluence_pages', ['author_id'], unique=False, schema='normalized')
    op.create_index('idx_confluence_pages_space', 'confluence_pages', ['space_id'], unique=False, schema='normalized')
    op.create_index('idx_confluence_pages_updated', 'confluence_pages', ['updated_at'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_confluence_pages_author_id'), 'confluence_pages', ['author_id'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_confluence_pages_space_id'), 'confluence_pages', ['space_id'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_confluence_pages_updated_at'), 'confluence_pages', ['updated_at'], unique=False, schema='normalized')
    op.create_table('github_issue_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('repo_full_name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('external_event_id', sa.Integer(), nullable=False),
    sa.Column('actor_login', sa.String(length=255), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('detail_login', sa.String(length=255), nullable=True),
    sa.Column('detail_id', sa.Integer(), nullable=True),
    sa.Column('commit_id', sa.String(length=40), nullable=True),
    sa.Column('commit_url', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='normalized'
    )
    op.create_index('idx_github_events_created_at', 'github_issue_events', ['created_at'], unique=False, schema='normalized')
    op.create_index('idx_github_events_event_type', 'github_issue_events', ['event_type'], unique=False, schema='normalized')
    op.create_index('idx_github_events_issue', 'github_issue_events', ['issue_id'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_github_issue_events_created_at'), 'github_issue_events', ['created_at'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_github_issue_events_external_event_id'), 'github_issue_events', ['external_event_id'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_github_issue_events_issue_id'), 'github_issue_events', ['issue_id'], unique=False, schema='normalized')
    op.create_table('github_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_integration_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('repo_full_name', sa.String(length=255), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('author_login', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('assignee_login', sa.String(length=255), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('milestone_title', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('snapshot_version', sa.Integer(), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='normalized'
    )
    op.create_index('idx_github_issues_assignee', 'github_issues', ['assignee_login'], unique=False, schema='normalized')
    op.create_index('idx_github_issues_repo', 'github_issues', ['repo_full_name'], unique=False, schema='normalized')
    op.create_index('idx_github_issues_state', 'github_issues', ['state'], unique=False, schema='normalized')
    op.create_index('idx_github_issues_updated', 'github_issues', ['updated_at'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_github_issues_assignee_login'), 'github_issues', ['assignee_login'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_github_issues_author_login'), 'github_issues', ['author_login'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_github_issues_issue_id'), 'github_issues', ['issue_id'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_github_issues_project_integration_id'), 'github_issues', ['project_integration_id'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_github_issues_repo_full_name'), 'github_issues', ['repo_full_name'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_github_issues_state'), 'github_issues', ['state'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_github_issues_updated_at'), 'github_issues', ['updated_at'], unique=False, schema='normalized')
    op.create_table('issue_changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_key', sa.String(length=255), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('from_value', sa.String(length=255), nullable=True),
    sa.Column('to_value', sa.String(length=255), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('author_account_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='normalized'
    )
    op.create_index('idx_changelog_changed_at', 'issue_changelog', ['changed_at'], unique=False, schema='normalized')
    op.create_index('idx_changelog_field', 'issue_changelog', ['field_name'], unique=False, schema='normalized')
    op.create_index('idx_changelog_issue_key', 'issue_changelog', ['issue_key'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_issue_changelog_issue_key'), 'issue_changelog', ['issue_key'], unique=False, schema='normalized')
    op.create_table('jira_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_integration_id', sa.Integer(), nullable=True),
    sa.Column('issue_key', sa.String(length=255), nullable=False),
    sa.Column('project_key', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('status_category', sa.String(length=50), nullable=True),
    sa.Column('assignee_account_id', sa.String(length=255), nullable=True),
    sa.Column('assignee_name', sa.String(length=255), nullable=True),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('reporter_account_id', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('story_points', sa.Float(), nullable=True),
    sa.Column('original_estimate', sa.Float(), nullable=True),
    sa.Column('time_spent', sa.Float(), nullable=True),
    sa.Column('remaining_estimate', sa.Float(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('snapshot_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='normalized'
    )
    op.create_index(op.f('ix_normalized_jira_issues_assignee_account_id'), 'jira_issues', ['assignee_account_id'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_jira_issues_closed_at'), 'jira_issues', ['closed_at'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_jira_issues_issue_key'), 'jira_issues', ['issue_key'], unique=True, schema='normalized')
    op.create_index(op.f('ix_normalized_jira_issues_project_integration_id'), 'jira_issues', ['project_integration_id'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_jira_issues_project_key'), 'jira_issues', ['project_key'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_jira_issues_status'), 'jira_issues', ['status'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_jira_issues_updated_at'), 'jira_issues', ['updated_at'], unique=False, schema='normalized')
    op.create_table('project_status_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_key', sa.String(length=255), nullable=False),
    sa.Column('status_name', sa.String(length=100), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('is_in_progress', sa.Boolean(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('jira_category', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('synced_by_account_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_key', 'status_name', name='uq_project_status'),
    schema='normalized'
    )
    op.create_index('idx_project_status_mappings_project', 'project_status_mappings', ['project_key'], unique=False, schema='normalized')
    op.create_index('idx_project_status_mappings_status', 'project_status_mappings', ['status_name'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_project_status_mappings_project_key'), 'project_status_mappings', ['project_key'], unique=False, schema='normalized')
    op.create_table('raw_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('project_integration_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_index('idx_raw_events_source_external', 'raw_events', ['source', 'external_id'], unique=False, schema='raw')
    op.create_index('idx_raw_events_timestamp', 'raw_events', ['timestamp'], unique=False, schema='raw')
    op.create_index(op.f('ix_raw_raw_events_event_type'), 'raw_events', ['event_type'], unique=False, schema='raw')
    op.create_index(op.f('ix_raw_raw_events_external_id'), 'raw_events', ['external_id'], unique=False, schema='raw')
    op.create_index(op.f('ix_raw_raw_events_source'), 'raw_events', ['source'], unique=False, schema='raw')
    op.create_index(op.f('ix_raw_raw_events_timestamp'), 'raw_events', ['timestamp'], unique=False, schema='raw')
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('lead_account_id', sa.String(length=255), nullable=True),
    sa.Column('jira_project_key', sa.String(length=50), nullable=True),
    sa.Column('confluence_space_key', sa.String(length=255), nullable=True),
    sa.Column('github_repo', sa.String(length=255), nullable=True),
    sa.Column('github_instance_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['identity.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_projects_github_repo'), 'projects', ['github_repo'], unique=False, schema='core')
    op.create_index(op.f('ix_core_projects_jira_project_key'), 'projects', ['jira_project_key'], unique=False, schema='core')
    op.create_index(op.f('ix_core_projects_key'), 'projects', ['key'], unique=True, schema='core')
    op.create_index(op.f('ix_core_projects_lead_account_id'), 'projects', ['lead_account_id'], unique=False, schema='core')
    op.create_table('integration_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('instance_id', sa.String(length=255), nullable=False),
    sa.Column('instance_name', sa.String(length=255), nullable=True),
    sa.Column('instance_url', sa.String(length=500), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'instance_id', name='uq_user_provider_instance'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_integration_tokens_instance_id'), 'integration_tokens', ['instance_id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_integration_tokens_provider'), 'integration_tokens', ['provider'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_integration_tokens_provider_user_id'), 'integration_tokens', ['provider_user_id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_integration_tokens_user_id'), 'integration_tokens', ['user_id'], unique=False, schema='identity')
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('client_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_sessions_session_token'), 'sessions', ['session_token'], unique=True, schema='identity')
    op.create_index(op.f('ix_identity_sessions_user_id'), 'sessions', ['user_id'], unique=False, schema='identity')
    op.create_table('confluence_comments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('page_id', sa.String(length=50), nullable=False),
    sa.Column('author_id', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['normalized.confluence_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='normalized'
    )
    op.create_index('idx_comments_author', 'confluence_comments', ['author_id'], unique=False, schema='normalized')
    op.create_index('idx_comments_page', 'confluence_comments', ['page_id'], unique=False, schema='normalized')
    op.create_index('idx_comments_resolved', 'confluence_comments', ['is_resolved'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_confluence_comments_author_id'), 'confluence_comments', ['author_id'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_confluence_comments_is_resolved'), 'confluence_comments', ['is_resolved'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_confluence_comments_page_id'), 'confluence_comments', ['page_id'], unique=False, schema='normalized')
    op.create_table('confluence_page_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=50), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('author_id', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('minor_edit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['normalized.confluence_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='normalized'
    )
    op.create_index('idx_page_versions_page', 'confluence_page_versions', ['page_id', 'version_number'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_confluence_page_versions_author_id'), 'confluence_page_versions', ['author_id'], unique=False, schema='normalized')
    op.create_index(op.f('ix_normalized_confluence_page_versions_page_id'), 'confluence_page_versions', ['page_id'], unique=False, schema='normalized')
    op.create_table('user_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['core.projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_user_project'),
    schema='core'
    )
    op.create_index(op.f('ix_core_user_projects_project_id'), 'user_projects', ['project_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_user_projects_user_id'), 'user_projects', ['user_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_user_projects_user_id'), table_name='user_projects', schema='core')
    op.drop_index(op.f('ix_core_user_projects_project_id'), table_name='user_projects', schema='core')
    op.drop_table('user_projects', schema='core')
    op.drop_index(op.f('ix_normalized_confluence_page_versions_page_id'), table_name='confluence_page_versions', schema='normalized')
    op.drop_index(op.f('ix_normalized_confluence_page_versions_author_id'), table_name='confluence_page_versions', schema='normalized')
    op.drop_index('idx_page_versions_page', table_name='confluence_page_versions', schema='normalized')
    op.drop_table('confluence_page_versions', schema='normalized')
    op.drop_index(op.f('ix_normalized_confluence_comments_page_id'), table_name='confluence_comments', schema='normalized')
    op.drop_index(op.f('ix_normalized_confluence_comments_is_resolved'), table_name='confluence_comments', schema='normalized')
    op.drop_index(op.f('ix_normalized_confluence_comments_author_id'), table_name='confluence_comments', schema='normalized')
    op.drop_index('idx_comments_resolved', table_name='confluence_comments', schema='normalized')
    op.drop_index('idx_comments_page', table_name='confluence_comments', schema='normalized')
    op.drop_index('idx_comments_author', table_name='confluence_comments', schema='normalized')
    op.drop_table('confluence_comments', schema='normalized')
    op.drop_index(op.f('ix_identity_sessions_user_id'), table_name='sessions', schema='identity')
    op.drop_index(op.f('ix_identity_sessions_session_token'), table_name='sessions', schema='identity')
    op.drop_table('sessions', schema='identity')
    op.drop_index(op.f('ix_identity_integration_tokens_user_id'), table_name='integration_tokens', schema='identity')
    op.drop_index(op.f('ix_identity_integration_tokens_provider_user_id'), table_name='integration_tokens', schema='identity')
    op.drop_index(op.f('ix_identity_integration_tokens_provider'), table_name='integration_tokens', schema='identity')
    op.drop_index(op.f('ix_identity_integration_tokens_instance_id'), table_name='integration_tokens', schema='identity')
    op.drop_table('integration_tokens', schema='identity')
    op.drop_index(op.f('ix_core_projects_lead_account_id'), table_name='projects', schema='core')
    op.drop_index(op.f('ix_core_projects_key'), table_name='projects', schema='core')
    op.drop_index(op.f('ix_core_projects_jira_project_key'), table_name='projects', schema='core')
    op.drop_index(op.f('ix_core_projects_github_repo'), table_name='projects', schema='core')
    op.drop_table('projects', schema='core')
    op.drop_index(op.f('ix_raw_raw_events_timestamp'), table_name='raw_events', schema='raw')
    op.drop_index(op.f('ix_raw_raw_events_source'), table_name='raw_events', schema='raw')
    op.drop_index(op.f('ix_raw_raw_events_external_id'), table_name='raw_events', schema='raw')
    op.drop_index(op.f('ix_raw_raw_events_event_type'), table_name='raw_events', schema='raw')
    op.drop_index('idx_raw_events_timestamp', table_name='raw_events', schema='raw')
    op.drop_index('idx_raw_events_source_external', table_name='raw_events', schema='raw')
    op.drop_table('raw_events', schema='raw')
    op.drop_index(op.f('ix_normalized_project_status_mappings_project_key'), table_name='project_status_mappings', schema='normalized')
    op.drop_index('idx_project_status_mappings_status', table_name='project_status_mappings', schema='normalized')
    op.drop_index('idx_project_status_mappings_project', table_name='project_status_mappings', schema='normalized')
    op.drop_table('project_status_mappings', schema='normalized')
    op.drop_index(op.f('ix_normalized_jira_issues_updated_at'), table_name='jira_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_jira_issues_status'), table_name='jira_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_jira_issues_project_key'), table_name='jira_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_jira_issues_project_integration_id'), table_name='jira_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_jira_issues_issue_key'), table_name='jira_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_jira_issues_closed_at'), table_name='jira_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_jira_issues_assignee_account_id'), table_name='jira_issues', schema='normalized')
    op.drop_table('jira_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_issue_changelog_issue_key'), table_name='issue_changelog', schema='normalized')
    op.drop_index('idx_changelog_issue_key', table_name='issue_changelog', schema='normalized')
    op.drop_index('idx_changelog_field', table_name='issue_changelog', schema='normalized')
    op.drop_index('idx_changelog_changed_at', table_name='issue_changelog', schema='normalized')
    op.drop_table('issue_changelog', schema='normalized')
    op.drop_index(op.f('ix_normalized_github_issues_updated_at'), table_name='github_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_github_issues_state'), table_name='github_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_github_issues_repo_full_name'), table_name='github_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_github_issues_project_integration_id'), table_name='github_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_github_issues_issue_id'), table_name='github_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_github_issues_author_login'), table_name='github_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_github_issues_assignee_login'), table_name='github_issues', schema='normalized')
    op.drop_index('idx_github_issues_updated', table_name='github_issues', schema='normalized')
    op.drop_index('idx_github_issues_state', table_name='github_issues', schema='normalized')
    op.drop_index('idx_github_issues_repo', table_name='github_issues', schema='normalized')
    op.drop_index('idx_github_issues_assignee', table_name='github_issues', schema='normalized')
    op.drop_table('github_issues', schema='normalized')
    op.drop_index(op.f('ix_normalized_github_issue_events_issue_id'), table_name='github_issue_events', schema='normalized')
    op.drop_index(op.f('ix_normalized_github_issue_events_external_event_id'), table_name='github_issue_events', schema='normalized')
    op.drop_index(op.f('ix_normalized_github_issue_events_created_at'), table_name='github_issue_events', schema='normalized')
    op.drop_index('idx_github_events_issue', table_name='github_issue_events', schema='normalized')
    op.drop_index('idx_github_events_event_type', table_name='github_issue_events', schema='normalized')
    op.drop_index('idx_github_events_created_at', table_name='github_issue_events', schema='normalized')
    op.drop_table('github_issue_events', schema='normalized')
    op.drop_index(op.f('ix_normalized_confluence_pages_updated_at'), table_name='confluence_pages', schema='normalized')
    op.drop_index(op.f('ix_normalized_confluence_pages_space_id'), table_name='confluence_pages', schema='normalized')
    op.drop_index(op.f('ix_normalized_confluence_pages_author_id'), table_name='confluence_pages', schema='normalized')
    op.drop_index('idx_confluence_pages_updated', table_name='confluence_pages', schema='normalized')
    op.drop_index('idx_confluence_pages_space', table_name='confluence_pages', schema='normalized')
    op.drop_index('idx_confluence_pages_author', table_name='confluence_pages', schema='normalized')
    op.drop_table('confluence_pages', schema='normalized')
    op.drop_index(op.f('ix_identity_users_email'), table_name='users', schema='identity')
    op.drop_table('users', schema='identity')
    # ### end Alembic commands ###
