"""make_atlassian_account_id_nullable

Revision ID: c47b0d23d3a3
Revises: d320eefdaae5
Create Date: 2026-03-30 07:11:46.822713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47b0d23d3a3'
down_revision: Union[str, Sequence[str], None] = 'd320eefdaae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
